# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApp
  pod 'GoogleMaps'
  pod 'Alamofire', '~> 5.0.0-rc.3'

  target 'DemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoAppUITests' do
    # Pods for testing
  end

end
